export const SHOW_LOADING = 'show_loading'
export const HIDE_LOADING = 'hide_loading'
export const AUTH_SUCCESS = 'auth_success'
export const ERROR_MSG = 'error_msg'
export const UPDATE_USER = 'update_user'
export const RESET_ERROR = 'reset_error'
export const SET_ROUTERS = 'set_routers'